### ISSUE TITLE
Add encoding for JPEG 2000 Lossless transfer syntax

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pylibjpeg-openjpeg#28]

**Comment by CPBridge** [comment]
Hi @scaramallion, we would be very interested in having this feature available for some applications in [highdicom](https://github.com/ImagingDataCommons/highdicom). What would it take to enable it?

If feasible, we may be able to help to some extent.

cc @dclunie @fedorov

**Comment by scaramallion** [comment]
You'd need to write the encoder and Python interface and supporting tests. Optionally you could add the encoder plugin to pydicom but strictly speaking that's not necessary.

**Comment by scaramallion** [comment]
For reference, [here is the table of pixel data attributes](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.4.html) that can be used with J2K in DICOM

**Comment by dclunie** [comment]
FYI, that table is not quite correct, since I inadvertently specified some restrictions when I did CP 1653 that added this summary table, which are not actually present. See CP [2301](https://dicom.nema.org/medical/dicom/CP/cp2301_vp_singleBitRLEandJ2KforSEG.pdf).

**Comment by CPBridge** [comment]
Yes, numpy arrays would be preferable from my point of view. Thanks!

**Comment by dclunie** [comment]
How does numpy handle bilevel data (array of booleans)? I came across https://stackoverflow.com/questions/5602155/numpy-boolean-array-with-1-bit-entries

**Comment by scaramallion** [comment]
The underlying itemsize is 8-bit, so the input array size won't be memory optimised. Is that a problem?

If you have some other preferred data object I can probably write a separate function for encoding 1-bit data.

**Comment by CPBridge** [comment]
I don't personally foresee this as a problem. Certainly we could pass raw `bytes` objects backwards and forwards as an alternative. However, since pretty much the entire scientific python ecosystem works with numpy arrays as the fundamental datatype, it's going to be extremely unusual for someone to produce or use a segmentation mask in any other form (especially one that is truly bit-packed), so they will be paying the memory cost anyway.

**Comment by scaramallion** [comment]
OK @CPBridge, all done. Do you mind testing out the release?

For segmentations I think you should just be able to do:
```python
from openjpeg import encode

b = encode(arr)
```
