### ISSUE TITLE
Publish manylinux_aarch64 wheels

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pydicom/pylibjpeg-openjpeg#56]
Would it be possible to also publish wheels for linux arm architecture?

**Comment by mrbean-bremen** [comment]
It should be the same as for `pylibjpeg-libjpeg`, so this should be easy - provided that that one works correctly. I will wait for a confirmation first...

**Comment by mrbean-bremen** [comment]
Ok, I did not wait and published a new patch release. Please check if the wheels work for you.

**Comment by mrbean-bremen** [comment]
I'm closing this as done, please reopen if there are problems.

**Comment by berendkleinhaneveld** [comment]
Thanks for fixing this! Sorry for not getting back to you yet: I ran into some trouble with another python package which prevents me from actually running/testing the new wheel in our code base/environment. 
Thanks for the quick response!
