### ISSUE TITLE
Add support for High Throughput JPEG2000

### ISSUE THREAD

**Issue by darcymason** [pydicom/pylibjpeg-openjpeg#60]
See https://github.com/pydicom/pydicom/issues/1848.

**Comment by darcymason** [comment]
Links:

Sup235 status: https://www.dclunie.com/dicom-status/status.html#Supplement235
Sup235 (WIP) document: https://www.dicomstandard.org/news-dir/current/docs/sups/sup235.pdf

Sample images (pointed to in pydicom/pydicom#1848):  
All at 'https://pacsbin-util.s3.amazonaws.com/test-images/htj2k/' + ..
        `1.jph.dcm`
        `xray-<n>.jph.dcm` where `<n>` = 1-10

**Comment by dazzag24** [comment]
Does this close https://github.com/pydicom/pydicom/issues/1848? or is further work in PyDicom itself required to complete support for HTJ2K?

Thanks
Darren

**Comment by scaramallion** [comment]
Oh, and not with the most recent release of `pylibjpeg` itself with Python 3.12, it needs the current `main` version.

**Comment by scaramallion** [comment]
v2 of pylibjpeg and pylibjpeg-openjpeg have been released, wheels are available.
