### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by erfelipe2** [pydicom/pylibjpeg-openjpeg#79]
## Dear, when try to install with pip, a problem occur:

Building wheel for pylibjpeg-openjpeg (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for pylibjpeg-openjpeg (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [40 lines of output]
fatal: not a git repository (or any of the parent directories): .git
A setup.py file already exists. Using it.

ERROR: Failed building wheel for pylibjpeg-openjpeg
Failed to build pylibjpeg-openjpeg
ERROR: Could not build wheels for pylibjpeg-openjpeg, which is required to install pyproject.toml-based projects

### Enviroment:
Python 3.11.3
pip 23.3.2
MacOS 14.2.1

**Comment by scaramallion** [comment]
Can you post the output from `pip install -v`?

**Comment by erfelipe** [comment]
> Can you post the full output from `pip install -v pylibjpeg-openjpeg`?

(venv) ➜  dicom pip install -v pylibjpeg-openjpeg
Using pip 23.3.2 from /Users/eduardof./Documents/Workspace/dicom/venv/lib/python3.11/site-packages/pip (python 3.11)
Collecting pylibjpeg-openjpeg
  Using cached pylibjpeg_openjpeg-2.1.0.tar.gz (2.0 MB)
  Running command pip subprocess to install build dependencies
  Collecting poetry-core<2,>=1.8
    Using cached poetry_core-1.8.1-py3-none-any.whl.metadata (3.5 kB)
  Collecting numpy>=1.24
    Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (115 kB)
  Collecting cython>=3.0
    Using cached Cython-3.0.8-py2.py3-none-any.whl.metadata (3.2 kB)
  Collecting setuptools
    Using cached setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
  Using cached poetry_core-1.8.1-py3-none-any.whl (306 kB)
  Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
  Using cached Cython-3.0.8-py2.py3-none-any.whl (1.2 MB)
  Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
  Installing collected packages: setuptools, poetry-core, numpy, cython
  Successfully installed cython-3.0.8 numpy-1.26.3 poetry-core-1.8.1 setuptools-69.0.3
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... done
  Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/3a/be/650f9c091ef71cb01d735775d554e068752d3ff63d7943b26316dc401749/numpy-1.21.2.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/5f/d6/ad58ded26556eaeaa8c971e08b6466f17c4ac4d786cd3d800e26ce59cc01/numpy-1.21.3.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.11.3 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (from https://pypi.org/simple/numpy/) (requires-python:>=3.7,<3.11)
Collecting numpy<2.0,>=1.24 (from pylibjpeg-openjpeg)
  Obtaining dependency information for numpy<2.0,>=1.24 from https://files.pythonhosted.org/packages/55/78/f85aab3bda3ddffe6ce8c590190b5f0d2e61dfd2fb7a8f446dcb4f8c12c7/numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (115 kB)
Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Building wheels for collected packages: pylibjpeg-openjpeg
  Running command Building wheel for pylibjpeg-openjpeg (pyproject.toml)
  fatal: not a git repository (or any of the parent directories): .git
  A setup.py file already exists. Using it.
  Traceback (most recent call last):
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/setup.py", line 47, in <module>
      build(setup_kwargs)
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/build.py", line 26, in build
      setup_oj()
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/build.py", line 134, in setup_oj
      subprocess.call(['cmake', os.fspath((LIB_DIR / "openjpeg").resolve(strict=True))])
    File "/Users/eduardof./.pyenv/versions/3.11.3/lib/python3.11/subprocess.py", line 389, in call
      with Popen(*popenargs, **kwargs) as p:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/eduardof./.pyenv/versions/3.11.3/lib/python3.11/subprocess.py", line 1024, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Users/eduardof./.pyenv/versions/3.11.3/lib/python3.11/subprocess.py", line 1917, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
  Traceback (most recent call last):
    File "/Users/eduardof./Documents/Workspace/dicom/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/eduardof./Documents/Workspace/dicom/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/eduardof./Documents/Workspace/dicom/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-build-env-k44bjgtg/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
      return WheelBuilder.make_in(
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-build-env-k44bjgtg/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
      wb.build(target_dir=directory)
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-build-env-k44bjgtg/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in build
      self._build(zip_file)
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-build-env-k44bjgtg/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 182, in _build
      self._run_build_command(setup)
    File "/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-build-env-k44bjgtg/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 250, in _run_build_command
      subprocess.check_call(
    File "/Users/eduardof./.pyenv/versions/3.11.3/lib/python3.11/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/Users/eduardof./Documents/Workspace/dicom/venv/bin/python', '/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/setup.py', 'build', '-b', '/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/build', '--build-purelib', '/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/build/lib', '--build-platlib', '/private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e/build/lib.macosx-13.3-arm64-cpython-311']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Building wheel for pylibjpeg-openjpeg (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/eduardof./Documents/Workspace/dicom/venv/bin/python /Users/eduardof./Documents/Workspace/dicom/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/tmpdjdlh51m
  cwd: /private/var/folders/66/216vt7497zn2ptksjgkgx02m0000gn/T/pip-install-niq4a_rx/pylibjpeg-openjpeg_e3f410cf86ce426397b91cc299942b5e
  Building wheel for pylibjpeg-openjpeg (pyproject.toml) ... error
  ERROR: Failed building wheel for pylibjpeg-openjpeg
Failed to build pylibjpeg-openjpeg
ERROR: Could not build wheels for pylibjpeg-openjpeg, which is required to install pyproject.toml-based projects

**Comment by scaramallion** [comment]
What Apple hardware are you running on?

**Comment by scaramallion** [comment]
If you need an immediate fix then you can install `cmake` to fix the build process. 

I'll see if I can build some wheels for ARM on MacOS and upload them to pypi.

**Comment by erfelipe** [comment]
> What Apple hardware are you running on?
> 
> Ideally there should already be a suitable wheel available, but clearly that's not true. Failing that you should be able to build from source, but that requires `cmake` to be installed so the configuration step works.

Don't worry @scaramallion  I found another way (lib) to solve the problem. 
But if it helps, the hardware is a MacBook Pro 14" (arm) with the latest version of Sonoma 14.2.1 
A C++ compiler for VS Code is installed on the machine, as well as XCode and Android Studio. So it's quite strange that he couldn't find a compiler for c++. 
But I understand that you found the problem point in this type of configuration. 
Thank you for your attention. Maybe this future fix will help other users.

**Comment by scaramallion** [comment]
I've added some wheels [here](https://github.com/pydicom/pylibjpeg-openjpeg/releases/tag/v2.1.0) in the meantime. Could you do me a favour and test the appropriate one to make sure it's working?

**Comment by erfelipe** [comment]
> I've added some wheels [here](https://github.com/pydicom/pylibjpeg-openjpeg/releases/tag/v2.1.0) in the meantime. Could you do me a favour and test the appropriate one to make sure it's working?

(venv) ➜  dicom pip install pylibjpeg_openjpeg-2.1.0-cp**310**-cp310-macosx_12_0_arm64.whl
ERROR: pylibjpeg_openjpeg-2.1.0-cp310-cp310-macosx_12_0_arm64.whl is not a supported wheel on this platform.

(venv) ➜  dicom pip install pylibjpeg_openjpeg-2.1.0-cp**311**-cp311-macosx_12_0_arm64.whl
Processing ./pylibjpeg_openjpeg-2.1.0-cp311-cp311-macosx_12_0_arm64.whl
Collecting numpy<2.0,>=1.24 (from pylibjpeg-openjpeg==2.1.0)
  Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (115 kB)
Using cached numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Installing collected packages: numpy, pylibjpeg-openjpeg
Successfully installed numpy-1.26.3 pylibjpeg-openjpeg-2.1.0

----

311 version works. 

(venv) ➜  dicom pip list
Package            Version
------------------ -------
numpy              1.26.3
pip                23.3.2
pydicom            2.4.4
pylibjpeg-openjpeg 2.1.0
setuptools         65.5.0

--------

(venv) ➜  dicom pip install pylibjpeg_openjpeg-2.1.0-**cp312**-cp312-macosx_12_0_arm64.whl
ERROR: pylibjpeg_openjpeg-2.1.0-cp312-cp312-macosx_12_0_arm64.whl is not a supported wheel on this platform.

(venv) ➜  dicom pip install pylibjpeg_openjpeg-2.1.0-**cp39**-cp39-macosx_12_0_arm64.whl
ERROR: pylibjpeg_openjpeg-2.1.0-cp39-cp39-macosx_12_0_arm64.whl is not a supported wheel on this platform.

**Comment by scaramallion** [comment]
The failures are all with a Python 3.11 venv?

**Comment by erfelipe** [comment]
> The failures are all with a Python 3.11 venv?

Yeap
(venv) ➜  dicom python --version
Python 3.11.3

The another versions break. The cp311 works. 
Do you need another test in Python LTS? 3.12 ? I can look for update and repeat the install from that files again.

**Comment by scaramallion** [comment]
No, that's fine, thanks for your help

**Comment by scaramallion** [comment]
OK, the wheels are up on PyPI. Thanks again
